export const CHANGE_SQUARE_COLOR_SUCCESS = "CHANGE_SQUARE_COLOR_SUCCESS";

export const CHANGE_SQUARE_COLOR_FAIL = "CHANGE_SQUARE_COLOR_FAIL";

export const RESET_GAME_PROCESS = "RESET_GAME_PROCESS";

export const SET_TIMER_INTERVAL = "SET_TIMER_INTERVAL";

export const FINISH_THE_GAME = "FINISH_THE_GAME";

export const START_THE_GAME = "START_THE_GAME";

